### ISSUE TITLE
Update Pre-Work to include Heroku and Postgres installation/proof of life

### ISSUE THREAD

**Issue by johncokos** [codefellows/code-301-prework#25]
These need also hook into the canvas assignment "Setup  your laptop"

Requires a screenshot to prove it.

**Comment by brookr** [comment]
@johncokos NB: Michelle added PostgreSQL instructions for WSL: https://github.com/codefellows/code-301-prework/pull/24#pullrequestreview-115732424

**Comment by michaeltreat** [comment]
[PR 30](https://github.com/codefellows/code-301-prework/pull/30) closes this issue.
