### ISSUE TITLE
Add CSS diner for test-in students

### ISSUE THREAD

**Issue by agrampa** [codefellows/code-301-prework#29]
https://flukeout.github.io/

**Comment by brookr** [comment]
Students submit a screenshot. 

Those who finished 201 should consider redoing it, or just state that they did it recently.

**Comment by mnfmnfm** [comment]
@brookr any updates on this almost-year-outstanding P0 issue?

**Comment by adrianhuebner** [comment]
Moved this issue to [301-react-guide](https://github.com/codefellows/code-301-guide-react/issues/64)
