### ISSUE TITLE
Fix dead link in README.md for jQuery intro course

### ISSUE THREAD

**Issue by DukeOfEtiquette** [codefellows/code-301-prework#35]
try.jquery.com currently redirects to the jquery.com landing page. Looks like a 301 Canvas course shows the Khan Academy intro jQuery course as the desired link: https://www.khanacademy.org/computing/computer-programming/html-js-jquery

If so, link needs updated to the Khan Academy link above to align the github pre-work repo to the Canvas assignment description.

**Comment by JB-Tellez** [comment]
Not sure why we went away from Khan academy. https://www.sololearn.com/Play/jQuery# is another option. But it's a good deal lighter on content.

**Comment by agrampa** [comment]
Fixed in this PR: https://github.com/codefellows/code-301-prework/pull/39

Changes Codecademy to Solo Learn
