### ISSUE TITLE
Add Portfolio prep prework

### ISSUE THREAD

**Issue by agrampa** [codefellows/code-301-prework#52]
In the new curriculum, 301 students will be building a personal portfolio in lab 4, then adding a few more features in lab 5. 

While they are already doing some career coaching assignments as prework, we can ask them to do just a little bit more, including:
- Professional pitch (Note that they already submit a recording in the current prework, so this would be submitting the text that goes along with whatever they say in the recording)
- Describe yourself in five words or less (to be used as a mini headline under their name, such as Joe Schmoe, Programming Ninja)
- Personal headline (a few sentences, the same type of information they would put as their headline on their LinkedIn page)
- What excites them about tech (one to two sentences)

If we find that this is asking too much of students, we can make it part of the lab 4 assignment.

If we do add it into the prework, we need to:
1) Time it accordingly with the Apprenti cohort's prework schedule
2) Decide if it should be added directly into the prework repo's README.md, or link out to something in the career coaching repo, like the other assignments.

**Comment by agrampa** [comment]
@brookr  I realized in lecture today, when discussing the prep for the portfolio assignment, that this had not been added to the prework yet.

**Comment by mnfmnfm** [comment]
@brookr any updates on this P0?

**Comment by adrianhuebner** [comment]
Both the code-301-react-guide and code-301-guide contain this as part of the prework!
