### ISSUE TITLE
wsl.md typo

### ISSUE THREAD

**Issue by rpruazol** [codefellows/code-301-prework#70]
# Issue
- Typo in wsl.md

# Cause
- The wsl.md document has a slight typo referring to `sudo service postgres start` rather than `sudo service postgresql start` in the "Suggestion" section, causing some confusion during set up

# Solution

(from the wsl.md doc)
## Suggestion

Since typing out `sudo service postgresl start` all the time can be tedious, and you'll need to run this when you restart your computer, we recommend you set up an alias for this.

# Final
N/A

**Comment by adrianhuebner** [comment]
@rpruazol I am closing this issue because everything is being moved to the https://github.com/codefellows/setup-guide/tree/master/code-301 and it is written without the mistake in that repo!
