### ISSUE TITLE
wsl.md instructions do not use homebrew

### ISSUE THREAD

**Issue by rpruazol** [codefellows/code-301-prework#72]
The directions in wsl.md do not have the homebrew instructions to install postgresql, which has causes issues with students who have postgres installed via homebrew AND `apt-get`.

Since we point students to https://github.com/codefellows/setup-guide/tree/master/code-301 now in Canvas for 301-prework materials, could we decommission this repo?

**Comment by adrianhuebner** [comment]
All prework is now handled by the prework setup-guide repo.
