### ISSUE TITLE
Inconstancy in docs between vscode and atom.

### ISSUE THREAD

**Issue by michaeltreat** [codefellows/code-301-prework#9]
Currently the prework says to install VScode instead of Atom, but later on in the doc is says to install linter and eslint for atom. This section needs to be updated to reflect how to install a linter for VScode.

**Comment by sjschmidt44** [comment]
@JB-Tellez This falls in line with the updates that you're making. 

At a glance, there are only a few extensions that we should have students install (confirm installation) in 301: 
1. Babel ES6/ES7
2. ESLint
3. File Icons (Not required, but good to have)
4. HTML CSS Support
5. Node.js Module Intellisense

Open to other suggestions, but those are the ones I've observed as being helpful for that level of development.

**Comment by JB-Tellez** [comment]
@sjschmidt44 @michaeltreat Submitted PR https://github.com/codefellows/code-301-prework/pull/10/commits to remove Atom references.

**Comment by JB-Tellez** [comment]
@sjschmidt44 In bullet point 1. Babel ES6/ES7 are you thinking students would have Babel transpiler installed as part of build process? Or just es6/es7 awareness in their ide?

**Comment by sjschmidt44** [comment]
No, this is just a syntax plugin so the editor is aware that they're working with ES6. In VS Code, it'll give them the 'language' option `javascript (babel)` to select.
